version: "2"
services:
  app:
    container_name: coupon
    restart: always
    build: .
    ports: 
      - "3000:3000"
    # links:
    depends_on:
      - mongo
    networks:
      - network
  
  mongo:
    container_name: mongo-coupon
    image: mongo
    volumes:
      - ~/Documents/perso/data/mongo/coupon:/data/db
    ports:
      - "27017:27017"
    networks:
      - network

networks:
  network:
    driver: bridge